### ISSUE TITLE
<enhancement><CLA폴더 만들기>

### ISSUE THREAD

**Issue by senajang** [senajang/SSIUM_UMBRELLA_RENTSYSTEM#29]
### 개요 ###
- CLA를 작성하고 관리를 하기 위하여 CLA폴더를 만들어야합니다

### 이슈 종류를 선택해주세요 ###
[-] New Feature
[ ] Bug Fix

### Type List ###
bug : Something isn't working
documentation : Improvements or additions to documentation
 duplicate : This issue or pull request already exists
 enhancement : new feature or request 
help wanted : Extra attention is needed
 invalid : This doesn't seem right
 question : Further information is requested
 wontfix : This will not be worked on

**Comment by doggina** [comment]
완료

**Comment by senajang** [comment]
완료
